// new Station(1,"Cote-Vertu",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Snowdon",["orange", "blue"],true,true,
    [[8, 3, "Open"],[7, 3, "Closed"],[6, 1, "Open"],[4, 3, "Closed"],[3, 2, "Open"],[2, 2, "Closed"]]), new Station(1,"Villa-Maria",["orange"],true,false,
    [[1, 1, "Monkland"]]), new Station(1,"Vendome",["orange"],true,false,
    [[3, 1, "Vendome"]]), new Station(1,"Place-Saint-Henri",["orange"],true,false,
    [[4, 3, "Only"]]), new Station(6,"Lionel-Groulx",["orange", "green"],true,true,
    [[8, 3, "Open"],[7, 3, "Closed"],[6, 1, "Open"],[4, 3, "Closed"],[3, 2, "Open"],[2, 2, "Closed"]]), new Station(1,"Georges-Vanier",["orange"],true,false,
    [[2, 3, "Only"]]), new Station(1,"Lucien-L'Allier",["orange"],true,false,
    [[8, 1, "Only"]]), new Station(1,"Bonaventure",["orange"],true,false,
    [[9, 2, "Only"]]), new Station(1,"Square-Victoria",["orange"],true,false,
    [[1, 3, "Only"]]), new Station(1,"Place-D'Armes",["orange"],true,false,
    [[5, 1, "Only"]]), new Station(1,"Champ-De-Mars",["orange"],true,false,
    [[6, 3, "Only"]]), new Station(1,"Berri-UQAM",["orange", "green"],true,true,
    [[8, 3, "Open"],[7, 3, "Closed"],[6, 1, "Open"],[4, 3, "Closed"],[3, 2, "Open"],[2, 2, "Closed"]]), new Station(1,"Sherbrooke",["orange"],true,false,
    [[1, 2, "Only"]]), new Station(1,"Mont-Royal",["orange"],true,false,
    [[4, 3, "Only"]]), new Station(1,"Laurier",["orange"],true,false,
    [[3, 3, "Only"]]), new Station(1,"Rosemont",["orange"],true,false,
    [[6, 2, "Only"]]), new Station(1,"Beaubien",["orange"],true,false,
    [[6, 2, "Only"]]), new Station(1,"Jean-Talon",["orange", "blue"],true,true,
[[8, 3, "Open"],[7, 3, "Closed"],[6, 1, "Open"],[4, 3, "Closed"],[3, 2, "Open"],[2, 2, "Closed"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["orange"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Atwater",["green"],true,false,
    [[2, 2, "Dawson"], [8, 2, "Atwater"]]), new Station(1,"Guy-Concordia",["green"],true,false,
    [[1, 1, "Concordia University"], [9, 3, "St. Mathieu"]]), new Station(1,"Peel",["green"],true,false,
    [[4, 1, "Only"]]), new Station(1,"McGill",["green"],true,false,
    [[2, 3, "Only"]]), new Station(1,"Place-des-Arts",["green"],true,false,
    [[7, 3, "Only"]]), new Station(1,"Saint-Laurent",["green"],true,false,
    [[6, 2, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 2, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[9, 2, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[4, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[3, 2, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[5, 3, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[5, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[1, 2, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[3, 2, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[2, 3, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[9, 1, "Only"]]), new Station(1,"Peel",["green"],true,false,
//     [[5, 2, "Only"]]), new Station(1,"Cote-des-Neiges",["blue"],true,false,
    [[8, 3, "Only"]]), new Station(1,"Universite-de-Montreal",["blue"],true,false,
    [[8, 2, "Only"]]), new Station(1,"Edouard Monpetit",["blue"],true,false,
    [[5, 3, "Only"]]), new Station(1,"Outremont",["blue"],true,false,
    [[7, 2, "Only"]]), new Station(1,"Acadie",["blue"],true,false,
    [[8, 1, "Only"]]), new Station(1,"Parc",["blue"],true,false,
    [[1, 1, "Only"]]), new Station(1,"de Castelnau",["blue"],true,false,
    [[1, 1, "Only"]]), new Station(1,"Peel",["blue"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["blue"],true,false,
//     [[1, 1, "Only"]]), new Station(1,"Peel",["blue"],true,false,
//     [[1, 1, "Only"]]),
